# Generated by Django 3.0.4 on 2020-04-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_instituicao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itens_doacao',
        ),
    ]
