# Generated by Django 3.0.4 on 2020-06-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_doador_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='senha',
            field=models.CharField(max_length=50),
        ),
    ]
