# Generated by Django 3.0.4 on 2020-06-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200602_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='registro',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='doador',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
