# Generated by Django 3.0.7 on 2020-06-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200607_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='data_doacao',
            field=models.DateField(),
        ),
    ]
