# Generated by Django 3.0.7 on 2020-06-10 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200607_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Instituicao'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='data_doacao',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='horario_doacao',
            field=models.CharField(max_length=8),
        ),
    ]
