# Generated by Django 3.0.7 on 2020-06-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200610_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='data_doacao',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='horario_doacao',
            field=models.CharField(max_length=20),
        ),
    ]
