# Generated by Django 3.0.7 on 2020-06-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_instituicao_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='imagem',
        ),
    ]
