# Generated by Django 3.0.7 on 2020-06-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_instituicao_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='img',
            field=models.CharField(default='', max_length=200),
        ),
    ]
